services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      # Server configuration (can be overridden in .env)
      - PORT=${PORT:-3001}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DEBUG=${DEBUG:-false}
    volumes:
      # Mount source code for development (remove in production)
      - .:/app
      # Exclude node_modules and other build artifacts
      - /app/.venv
      - /app/__pycache__
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

  # Optional: Add a development override service
  mcp-server-dev:
    extends:
      service: mcp-server
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    profiles:
      - dev

networks:
  mcp-network:
    driver: bridge

# Optional: Add volumes for persistent data if needed
# volumes:
#   mcp-data:
#     driver: local